In [1]:
import numpy as np

In [2]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
print(a[0])

[1 2 3 4]


In [6]:
import numpy as np
a = np.array([1, 2, 3])

In [7]:
np.zeros(2)

array([0., 0.])

In [8]:
np.ones(2)

array([1., 1.])

In [9]:
np.empty(2) 

array([1., 1.])

In [10]:
np.arange(4)

array([0, 1, 2, 3])

In [11]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [12]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [14]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [15]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [17]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim

3

In [20]:
array_example.size

24

In [21]:
array_example.shape

(3, 2, 4)

In [22]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [23]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [24]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [25]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [26]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [27]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [28]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [29]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [30]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [31]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [32]:
data = np.array([1, 2, 3])

data[1]

2

In [33]:
data[0:2]

array([1, 2])

In [34]:
data[1:]

array([2, 3])

In [35]:
data[-2:]

array([2, 3])

In [36]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


In [37]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [39]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [40]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [41]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [42]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [43]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [45]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [46]:
print(a[b])

[1 2 3 4]


In [47]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [48]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [49]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [50]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [51]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [52]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [53]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [54]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [55]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
b2 = a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [58]:
data - ones

array([0, 1])

In [59]:
data * data

array([1, 4])

In [60]:
data / data

array([1., 1.])

In [61]:
a = np.array([1, 2, 3, 4])

a.sum()

10

In [62]:
b = np.array([[1, 1], [2, 2]])

In [63]:
b.sum(axis=0)

array([3, 3])

In [64]:
b.sum(axis=1)

array([2, 4])

In [65]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [66]:
data.max()

2.0

In [67]:
data.min()

1.0

In [68]:
data.sum()

3.0

In [69]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

a.sum()

4.8595784

In [70]:
a.min()

0.05093587

In [71]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [72]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [73]:
data[0, 1]

2

In [74]:
data[1:3]


array([[3, 4],
       [5, 6]])

In [75]:
data[0:2, 0]

array([1, 3])

In [76]:
data.max()

6

In [77]:
data.min()

1

In [78]:
data.sum()

21

In [79]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [80]:
data.max(axis=0)

array([5, 6])

In [81]:
data.max(axis=1)

array([2, 5, 6])

In [82]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [83]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [84]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [85]:
np.ones(3)

array([1., 1., 1.])

In [86]:
np.zeros(3)

array([0., 0., 0.])

In [87]:
rng = np.random.default_rng()  
rng.random(3) 

array([0.49627673, 0.98588451, 0.59049135])

In [88]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [89]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [90]:
rng.random((3, 2)) 

array([[0.95553501, 0.4797622 ],
       [0.07872188, 0.05256949],
       [0.57971373, 0.32740457]])

In [91]:
rng.integers(5, size=(2, 4)) 

array([[1, 1, 3, 3],
       [2, 4, 4, 1]], dtype=int64)

In [92]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [93]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [94]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [95]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [96]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [97]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [98]:
print(indices)

[0 1 2]


In [99]:
print(occurrence_count)

[2 1 1]


In [100]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [102]:
arr = np.arange(6).reshape((2, 3))

arr

array([[0, 1, 2],
       [3, 4, 5]])

In [103]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [104]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [105]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [106]:
reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [107]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [108]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [109]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [110]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [111]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [112]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [113]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [114]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [115]:
a1 = x.flatten()
a1[0] = 99
print(x) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [116]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [117]:
a2 = x.ravel()
a2[0] = 98
print(x)  

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [118]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
